#!/usr/bin/env node
// Reads data/nansen-calls.jsonl (the append-only log nansen.ts writes on every real network
// call - see src/lib/nansen.ts logCall()) and prints a markdown summary a judge can check
// against the entry rule (100+ real Nansen calls during Sep 14-27). Also writes
// docs/API-CALLS.md so the README can link a static copy of the same summary.
import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";

const LOG_PATH = path.join(process.cwd(), "data", "nansen-calls.jsonl");
const OUT_PATH = path.join(process.cwd(), "docs", "API-CALLS.md");

async function main() {
  let raw;
  try {
    raw = await readFile(LOG_PATH, "utf8");
  } catch {
    console.log(`No call log yet at ${LOG_PATH}. Run the app against a real NANSEN_API_KEY first.`);
    return;
  }

  const lines = raw.split("\n").filter((l) => l.trim().length > 0);
  const entries = [];
  for (const line of lines) {
    try {
      entries.push(JSON.parse(line));
    } catch {
      // ponytail: skip a truncated last line rather than fail the whole report.
    }
  }

  if (entries.length === 0) {
    console.log(`${LOG_PATH} exists but has no parseable entries yet.`);
    return;
  }

  const byEndpoint = new Map();
  let successCount = 0;
  for (const e of entries) {
    byEndpoint.set(e.endpoint, (byEndpoint.get(e.endpoint) ?? 0) + 1);
    if (e.status >= 200 && e.status < 300) successCount++;
  }
  const sortedEndpoints = [...byEndpoint.entries()].sort((a, b) => b[1] - a[1]);
  const timestamps = entries.map((e) => e.ts).sort();
  const first = timestamps[0];
  const last = timestamps[timestamps.length - 1];
  const successRate = ((successCount / entries.length) * 100).toFixed(1);

  const md = [
    "# Nansen API call log",
    "",
    "Generated by `npm run calls:report` from `data/nansen-calls.jsonl`, which `src/lib/nansen.ts`",
    "appends to on every real network call (cache hits are never logged here). No apikey, header",
    "value, or signature material is ever written to this log.",
    "",
    `- Total real calls logged: **${entries.length}**`,
    `- Distinct endpoints: **${byEndpoint.size}**`,
    `- First call: ${first}`,
    `- Last call: ${last}`,
    `- Success rate: **${successRate}%** (${successCount}/${entries.length} with a 2xx status)`,
    "",
    "## Calls per endpoint",
    "",
    "| Endpoint | Calls |",
    "|---|---|",
    ...sortedEndpoints.map(([endpoint, count]) => `| \`${endpoint}\` | ${count} |`),
    "",
  ].join("\n");

  await mkdir(path.dirname(OUT_PATH), { recursive: true });
  await writeFile(OUT_PATH, md);
  console.log(md);
  console.log(`\nWrote ${OUT_PATH}`);
}

main();
