#!/usr/bin/env node
// Reads data/nansen-calls.jsonl (the append-only log nansen.ts writes on every real network
// call AND every cache hit - see src/lib/nansen.ts logCall()) and prints a markdown summary a
// judge can check against the entry rule (100+ real Nansen calls during Sep 14-27), plus how
// much the cache is doing so reuse is visible, not just raw volume. Also writes
// docs/API-CALLS.md so the README can link a static copy of the same summary.
import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";

const LOG_PATH = path.join(process.cwd(), "data", "nansen-calls.jsonl");
const OUT_PATH = path.join(process.cwd(), "docs", "API-CALLS.md");

async function main() {
  let raw;
  try {
    raw = await readFile(LOG_PATH, "utf8");
  } catch {
    console.log(`No call log yet at ${LOG_PATH}. Run the app against a real NANSEN_API_KEY first.`);
    return;
  }

  const lines = raw.split("\n").filter((l) => l.trim().length > 0);
  const entries = [];
  for (const line of lines) {
    try {
      entries.push(JSON.parse(line));
    } catch {
      // ponytail: skip a truncated last line rather than fail the whole report.
    }
  }

  if (entries.length === 0) {
    console.log(`${LOG_PATH} exists but has no parseable entries yet.`);
    return;
  }

  const real = entries.filter((e) => e.cache !== "hit");
  const hits = entries.filter((e) => e.cache === "hit");

  const byEndpoint = new Map();
  for (const e of entries) {
    const row = byEndpoint.get(e.endpoint) ?? { network: 0, hits: 0 };
    if (e.cache === "hit") row.hits++;
    else row.network++;
    byEndpoint.set(e.endpoint, row);
  }
  const sortedEndpoints = [...byEndpoint.entries()].sort((a, b) => (b[1].network + b[1].hits) - (a[1].network + a[1].hits));

  let successCount = 0;
  for (const e of real) if (e.status >= 200 && e.status < 300) successCount++;

  const timestamps = entries.map((e) => e.ts).sort();
  const first = timestamps[0];
  const last = timestamps[timestamps.length - 1];
  const successRate = real.length ? ((successCount / real.length) * 100).toFixed(1) : "0.0";

  const md = [
    "# Nansen API call log",
    "",
    "Generated by `npm run calls:report` from `data/nansen-calls.jsonl`, which `src/lib/nansen.ts`",
    "appends to on every real network call AND every cache hit (memory/disk/seed), so reuse is",
    "visible in the same log rather than invisible. No apikey, header value, or signature",
    "material is ever written to this log.",
    "",
    `- Real network calls: **${real.length}**`,
    `- Cache hits (avoided calls): **${hits.length}**`,
    `- Distinct endpoints: **${byEndpoint.size}**`,
    `- First entry: ${first}`,
    `- Last entry: ${last}`,
    `- Success rate on real calls: **${successRate}%** (${successCount}/${real.length} with a 2xx status)`,
    "",
    "## Per endpoint: real calls vs cache hits",
    "",
    "| Endpoint | Network calls | Cache hits |",
    "|---|---|---|",
    ...sortedEndpoints.map(([endpoint, r]) => `| \`${endpoint}\` | ${r.network} | ${r.hits} |`),
    "",
  ].join("\n");

  await mkdir(path.dirname(OUT_PATH), { recursive: true });
  await writeFile(OUT_PATH, md);
  console.log(md);
  console.log(`\nWrote ${OUT_PATH}`);
}

main();
